### ISSUE TITLE
inquiry about freebsd

### ISSUE THREAD

**Issue by allama1** [eborisch/ethname#1]
hi,

I've tried your script and it works perfectly. I'm using it on my pfsense setup as sometimes when i add new interfaces to the pfsense vm it changes the order of the network devices and messes up the whole config. I wanted to understand more from you whether this is a normal behavior of freebsd (even in virtual Environments) to just randomly change netwokr device names. in one instance I had 4 x vnics on pfsense (whic is running n freebsd) I remove the third vnic from the vm and add new one then I reboot the VM. when I do ifconfig I find that the what was once the 4th vnic now became the third and the new vnic I added is the 4th. is that how freebsd is designed to work?

**Comment by eborisch** [comment]
I would expect (on vanilla FreeBSD) the virtual NICs to be enumerated in the order presented by the VM host, but that order depends on your hypervisor; see, for example: https://www.reddit.com/r/vmware/comments/517y85/helpthe_order_of_network_interfaces_is_mismatched/

Obviously this script will help avoid any surprises by making the MAC address rather than presentation order the defining feature. Glad to hear it is working for you.

For your awareness the port is now available in sysutils/ethname in the ports tree.
